### ISSUE TITLE
Use System.nanoTime() instead of System.currentTimeMillis() in TaskBase.java

### ISSUE THREAD

**Issue by yoroto** [corretto/heapothesys#23]
Raised on behalf of @kuksenko . 

For measuring elapsed time, we should use System.nanoTime() here, as David Holmes [mentioned](https://web.archive.org/web/20160308031939/https://blogs.oracle.com/dholmes/entry/inside_the_hotspot_vm_clocks) a long time ago.

**Comment by kuksenko** [comment]
nanoTime() in not ideal. see https://shipilev.net/blog/2014/nanotrusting-nanotime/
But it's better than currentTimeMillis.
