### ISSUE TITLE
Shutdown threadpool when benchmark is done

### ISSUE THREAD

**Issue by johnoliver** [corretto/heapothesys#29]
When I run the benchmark the process does not exit when finished, seems due to the threads keeping the JVM alive, adding `executor.shutdown();` to SimpleRunner seems to solve this

**Comment by yoroto** [comment]
Hi @johnoliver 

Thank you for reporting this!

Does it always happen or only randomly? Do you have the commandline that can reproduce this  that I can give a try?

**Comment by johnoliver** [comment]
`java -Xmx1024m -Xloggc:/tmp/gc-am.log -jar ./target/Heapothesys-1.0.jar -a 100  -h 1024 -d 10 -c false -l /tmp/am.log`

**Comment by johnoliver** [comment]
For me it always happens

**Comment by AzeemJiva** [comment]
What version of Java are you using?  What hardware?

**Comment by yuhongye** [comment]
I use Mac OS 0.13.6, jdk version is "Java HotSpot(TM) 64-Bit Server VM (build 25.151-b12, mixed mode)", and it always happends too.

**Comment by AzeemJiva** [comment]
That's an old JDK8 build, can you run with something newer?

I recommend Corretto-8: https://docs.aws.amazon.com/corretto/latest/corretto-8-ug/downloads-list.html

**Comment by yuhongye** [comment]
OK, I will try it.

**Comment by kdnilsen** [comment]
Thank you for your suggestions.  We have added the executor.shutdown() invocation to allow the benchmark to terminate more cleanly.
